# Generated by Django 4.0.2 on 2022-04-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsecurite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.TextField(blank=True, default='pas encore livré', null=True),
        ),
    ]
