# Generated by Django 4.0.2 on 2022-04-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsecurite', '0003_commandenonlogin_date_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='resolution',
            field=models.TextField(choices=[('none', 'none'), ('1080', 'hd'), ('2160', 'hd+'), ('4320', '4k'), ('8640', '8k')], default='none'),
        ),
    ]
